### ISSUE TITLE
Better button card looks different with the same configuration from the original button card

### ISSUE THREAD

**Issue by ohadbenita** [Hypfer/better-button-card#1]
Hi,

I've been waiting for this for a long time, so first thank you for your efforts !
While attempting to migrate from button card I do see that the text alignment and colors are different (see attached picture)

[Before](https://i.imgur.com/iIifPQi.png) (original button card)
[After](https://i.imgur.com/k1tobe9.png) (better button card)

How can this be resolved ? (if at all it can)

Thanks

**Comment by Hypfer** [comment]
Thanks for pointing that out. The Text positioning is indeed a bug
There must be some css missing. I will look into this

The colored Icons however are a breaking change from button-card.
You need to add `color_style: icon` to every card where the icon should be in color.

**Comment by ohadbenita** [comment]
Thanks for the clarification and the fix, however it still has some [alignment issues](https://i.imgur.com/gDed85A.png)

**Comment by Hypfer** [comment]
Did you deploy the latest version and changed the version number to invalidate the cache?

**Comment by Hypfer** [comment]
Maybe show_state should be renamed to show_state_label to be more clear

**Comment by ohadbenita** [comment]
Yes ! this did the trick for removing the state name but surely didn't solve the alignment issues
Say @Hypfer where can I find the documentation of the new card to try some options with it ?

Thanks a lot for your responsiveness and help on this

**Comment by Hypfer** [comment]
For now there's the jsdoc found here

https://github.com/Hypfer/better-button-card/blob/master/better-button-card.js#L80

**Comment by ohadbenita** [comment]
I see, not too familiar with CSS styling options but I'll try to fiddle with it
Generally I'd like to be able to set the background, font color while off / unavailable & on, can you propose an example for that? if not - it's fine as well

**Comment by Hypfer** [comment]
I think the alignment should be fixed now.

**Comment by Hypfer** [comment]
Since the names i've copied over from button-card are also misleading when it comes to colors, I've changed the syntax yet again so you will have to update.

An example looks like this:
```
type: 'custom:better-button-card'
color_style: icon
entity: light.couchtisch
icon: 'mdi:lightbulb'
show_state_label: false
colors_by_state:
    on: "auto"
    off: "#000000"
    unavailable: "yellow"
    some_custom_state: "green"
```
